system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: True
  amp_level: 'O0'
  seed: 42
  val_while_train: True
  val_start_epoch: 100
  val_interval: 10
  drop_overflow_update: True

logger:
  log_dir: './tmp_det/log'

model:
  type: det
  transform: null
  backbone:
    name: det_resnet50
    pretrained: True
  neck:
    name: DBFPN
    out_channels: 256
    bias: False
    use_asf: False        # enable it for DB++
  head:
    name: DBHead
    k: 50
    bias: False
    adaptive: True

postprocess:
  name: DBPostprocess
  output_polygon: False   # whether to output a polygon or a box
  binary_thresh: 0.3      # binarization threshold
  box_thresh: 0.6         # box score threshold
  max_candidates: 1000
  expand_ratio: 1.5       # coefficient for expanding predictions

metric:
  name: DetMetric
  main_indicator: f-score

loss:
  name: L1BalancedCELoss
  eps: 1.0e-6
  l1_scale: 10
  bce_scale: 5
  bce_replace: bceloss

scheduler:
  scheduler: polynomial_decay
  min_lr: 0.
  lr: 0.007
  num_epochs: 1200
  warmup_epochs: 3

optimizer:
  opt: SGD
  filter_bias_and_bn: false
  momentum: 0.9
  weight_decay: 1.0e-4
  loss_scale: 1.0

train:
  ckpt_save_dir: './tmp_det/ckpt'
  dataset_sink_mode: False
  start_epoch: 0
  per_print_times: 10
  resume_ckpt: ''
  dataset:
    type: DetDataset
    dataset_root: /Users/Samit/Data/datasets 
    data_dir: ic15/det/train/ch4_training_images
    label_file: ic15/det/train/det_gt.txt
    sample_ratio: 1.0
    shuffle: True
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - DetLabelEncode:
      - MZResizeByGrid:
          divisor: 32
          transform_polys: True
      - MZRandomScaleByShortSide:
          short_side: 736
      - IaaAugment:
          augmenter_args:
            - { 'type': 'Affine', 'args': { 'rotate': [ -10, 10 ] } }
            - { 'type': 'Fliplr', 'args': { 'p': 0.5 } }
      - MZRandomCropData:
          max_tries: 100
          min_crop_side_ratio: 0.1
          crop_size: [ 640, 640 ]
      #- ShrinkBinaryMap:
      - MZMakeSegDetectionData:
          min_text_size: 8
          shrink_ratio: 0.4
      - BorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MZRandomColorAdjust:
          brightness: 0.1255 #32.0 / 255
          saturation: 0.5
          to_numpy: True
      - NormalizeImage:
          bgr_to_rgb: False
          is_hwc: True
          mean: imagenet
          std: imagenet
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize 
    output_columns: ['image', 'binary_map', 'mask', 'thresh_map', 'thresh_mask'] #'img_path']
    #output_columns: ['image'] # for debug op performance
    num_columns_to_net: 1 # num inputs for network forward func in output_columns

  loader:
    shuffle: True
    batch_size: 20
    drop_remainder: True
    num_workers: 8

eval:
  dataset_sink_mode: False
  dataset:
    type: DetDataset
    #dataset_root: /data/ocr_datasets 
    dataset_root: /Users/Samit/Data/datasets 
    data_dir: ic15/det/test/ch4_test_images
    label_file: ic15/det/test/det_gt.txt
    sample_ratio: 1.0
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          img_mode: RGB
          to_float32: False
      - DetLabelEncode:
      - MZResizeByGrid:
          divisor: 32
          transform_polys: True
      - MZScalePad:
          eval_size: [ 736, 1280 ] # h, w
      - NormalizeImage:
          bgr_to_rgb: False
          is_hwc: True
          mean: imagenet
          std: imagenet
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the labels for evalution 
    output_columns: [ 'image', 'polys', 'ignore_tags']
    num_columns_to_net: 1 # num inputs for network forward func
    #num_keys_of_labels: 2 # num labels 

  loader:
    shuffle: False
    batch_size: 1 # TODO: due to dynamic shape of polygons (num of boxes varies), BS has to be 1
    drop_remainder: False 
    num_workers: 1
